ssh_key_path: '' # Filled by the test
ssh_user: '' # Filled by the test
cloudify_license_path: '' # Filled by the test
manager_rpm_download_link: '' # Filled by the test

ldap:
  server: ''
  domain: ''
  is_active_directory: ''
  ca_cert: ''
  username: ''
  password: ''
  dn_extra: ''

ca_cert_path: ''

load_balancer_ip: ''

existing_vms:
    manager-1:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

    manager-2:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

    manager-3:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

    postgresql-1:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

    postgresql-2:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

    postgresql-3:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

    rabbitmq-1:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

    rabbitmq-2:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

    rabbitmq-3:
      private_ip: ''
      public_ip: ''
      hostname: ''
      cert_path: ''
      key_path: ''
      config_path: ''

credentials:
  manager:
    admin_username: 'admin'
    admin_password: 'admin'

  postgresql:
    postgres_password: ''
    cluster:
      etcd:
        cluster_token: ''
        root_password: ''
        patroni_password: ''
      patroni:
        rest_password: ''
      postgres:
        replicator_password: ''

  rabbitmq:
    username: ''
    password: ''
    erlang_cookie: ''

  prometheus:
    username: ''
    password: ''
